spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trade?characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true&autoReconnect=true
    username: trade
    password: trade123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-test-query: SELECT 1
  redis:
        db: 1
        host: localhost
        port: 6379
        password:
        lettuce:
          pool:
            max-active: 100
            max-idle: 100
            min-idle: 1
